kind: Pod
apiVersion: v1
metadata:
  name: p1
spec:
  hostPID: true
  containers:
    - name: p1
      image: jjong2/all:latest
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        privileged: true
      resources:
        limits:
          example.com/SLO1: "1"
          example.com/SLO2: "3"
  restartPolicy: Never
  nodeSelector:
    key: ubuntu4
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
